default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'db' %>
  port: <%= ENV['DB_PORT'] || '3306' %>

development:
  <<: *default
  database: tshirt_development

staging:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] || 'tshirt_production' %>
  username: <%= ENV['RDS_USERNAME'] || 'root' %>
  password: <%= ENV['RDS_PASSWORD'] || 'password' %>
  host: <%= ENV['RDS_HOSTNAME'] || 'db' %>
  port: <%= ENV['RDS_PORT'] || '3306' %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] || 'tshirt_production' %>
  username: <%= ENV['RDS_USERNAME'] || 'root' %>
  password: <%= ENV['RDS_PASSWORD'] || 'password' %>
  host: <%= ENV['RDS_HOSTNAME'] || 'db' %>
  port: <%= ENV['RDS_PORT'] || '3306' %>

test:
  <<: *default
  database: tshirt_test
